githubConfigUrl: "https://github.com/Tehedor/MLOps_actions_v2"
githubConfigSecret:
  github_token: "github_pat_*****"
maxRunners: 5
minRunners: 0
containerMode:
  type: "dind"
template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        resources:
          requests:
            cpu: "2"
            memory: "8Gi"
          limits:
            cpu: "4"
            memory: "8Gi"