runners:
  - GithubActions:
    max-parallel: 20
    labels: [ubuntu-latest]
  - CPU-self-hosted:
    max-parallel: 3
    labels: [self-hosted, CPU]
  - GPU-self-hosted:
    max-parallel: 3
    labels: [self-hosted, GPU]
  - ESP32-self-hosted:
    labels: [self-hosted, ESP32]
    max-parallel: 1

fases:
  - fase: f01_explore
    runner: "GithubActions, CPU-self-hosted"
    gh_fase: "f01_explore"
    parent_required: false
  - fase: f02_events
    runner: "GithubActions, CPU-self-hosted"
    gh_fase: "f02_events"
    parent_required: true
  - fase: f03_windows
    runner: "GithubActions, CPU-self-hosted"
    gh_fase: "f03_windows"
    parent_required: true
  - fase: f04_targets
    runner: "GithubActions, CPU-self-hosted"
    gh_fase: "f04_targets"
    parent_required: true
  - fase: f05_modeling
    runner: "GPU-self-hosted, CPU-self-hosted"
    gh_fase: "f05_modeling"
    parent_required: true
  - fase: f06_quant
    runner: "GithubActions, CPU-self-hosted"
    gh_fase: "f06_quant"
    parent_required: true
  - fase: f07_modval
    runner: '["self-hosted", "Linux", "X64", "self-hosted-tehelab"], ESP32-self-hosted, CPU-self-hosted'
    gh_fase: "f07_modval"
    parent_required: true
  - fase: f08_sysval
    runner: "GithubActions, CPU-self-hosted"
    gh_fase: "f08_sysval"
    parent_required: true